### ISSUE TITLE
Can we have a "Cull" button for the end of shift

### ISSUE THREAD

**Issue by marcltodd** [KirstyWright/cad-issue-tracker#10]
**Is your feature request related to a problem? Please describe.**
No doubt people in their infinite wisdom will forget to book off and as a dispatch team this button has been utilised a lot in the past.

**Describe the solution you'd like**
Have a button to mark all units as state 11

**Describe alternatives you've considered**
Non

**Additional context**
![image](https://user-images.githubusercontent.com/79205945/108248393-b2222480-714b-11eb-86a1-89aae7e7d8b5.png)

**Comment by KirstyWright** [comment]
at 23:00 it will remove everyone so no need to manually do it if not wanted.
