### ISSUE TITLE
Control fetures

### ISSUE THREAD

**Issue by Matt-Girvan** [KirstyWright/cad-issue-tracker#13]
When you hover over the cad as in #001 DRUGS when hovered over could that go a different colour say blue.

On the main page could the cad say how many units are attached on that cad

Could cross streets be implemented

**Comment by KirstyWright** [comment]
Reference `On the main page could the cad say how many units are attached on that cad`

On refresh the inital refresh is done against `/api/shifts/<num>/incidents` which contains a `units` array on every incident. However on websocket update there is no `units` which causes it to reset the numbers field. Comments update automatically so there is no problem with the refresh itself, I just need to include the units somehow.
