### ISSUE TITLE
Capitals

### ISSUE THREAD

**Issue by LCRPCFeenix** [KirstyWright/cad-issue-tracker#27]
Please put all text in CAPITALS - much like current Dispatcher/MDT.

Easier to read and looks more professional.

**Comment by KirstyWright** [comment]
I'm curious as to why you think it looks professional. 

It's a valid point that most current MDT systems run in full capital letters. But for scene logs and updates it makes the text harder to read to human eyes. It's the first time someone has suggested this so we shall have to see if more people like this idea.

**Comment by KirstyWright** [comment]
Closing as wontfix
